# Generated by Django 4.2.4 on 2023-08-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0002_delete_user_feedback_user_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmo.post'),
        ),
    ]
