# Generated by Django 4.2.4 on 2023-08-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0003_feedback_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
