# Generated by Django 4.2.4 on 2023-08-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmo', '0004_onetimecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
